### ISSUE TITLE
Make `spec` the default reporter

### ISSUE THREAD

**Issue by ldayananda** [videojs/videojs-generate-karma-config#14]
Compared to `dots`, `spec` gives more information on what tests ran, which ones passed and which failed in an easy to read format.

Example:

![image](https://user-images.githubusercontent.com/3826638/47815537-fc86f980-dd26-11e8-97bd-ed353b49dfeb.png)

**Comment by gkatsev** [comment]
I'm OK with making this be the default but will not be turning it on for Video.js. There are so many tests in there that run on enough browsers that it makes it impossible to see the entire log in travis.

**Comment by gkatsev** [comment]
Example: https://travis-ci.org/videojs/video.js/builds/449099544

**Comment by ldayananda** [comment]
Hmm, yeah looks like `spec` doesn't do too well when multiple browsers are run concurrently

**Comment by gkatsev** [comment]
I want a spec reporter that's smart enough to collate multiple browsers
into one output that makes sure it's obvious which browsers have the
failures.

**Comment by ldayananda** [comment]
Yeah, I was looking at [karma-mocha-reporter](https://www.npmjs.com/package/karma-mocha-reporter) briefly yesterday, which looks like it might have all those things. 

That said, [karma-spec-reporter](https://github.com/mlex/karma-spec-reporter/blob/master/README.md#configuration) has some configuration options that might help. `suppressErrorSummary: false, suppressPassed: true` might work the best for video.js core

**Comment by ldayananda** [comment]
Actually, looks like `suppressErrorSummary` defaults to `false`, so `suppressPassed: true` might be enough

**Comment by brandonocasey** [comment]
[karma-summary-reporter](https://www.npmjs.com/package/karma-summary-reporter) looks like it could work.

**Comment by gkatsev** [comment]
Giving summary-reporter with spec+suppressPassed a try over here https://travis-ci.org/videojs/video.js/builds/449407288
Once it passes, I'll make another change to show a breaking run. See changes here https://github.com/videojs/video.js/compare/try-spec?expand=1#diff-0be9d25d2ce091e16baef1e0d91d0cf7

**Comment by gkatsev** [comment]
Looks good but stack trace of my `assert.ok('false')` looks super weird https://travis-ci.org/videojs/video.js/builds/449412949

**Comment by ldayananda** [comment]
Ah, yeah that's what I saw recently too. But only with node 10 for some reason, and even then only for some tests

**Comment by gkatsev** [comment]
I'll try re-running it with node 8 to compare

**Comment by gkatsev** [comment]
nope, node 8 is having the same issue https://travis-ci.org/videojs/video.js/builds/449482685

**Comment by brandonocasey** [comment]
almost seems like a qunit issue, could be worth bumping its version back.

**Comment by brandonocasey** [comment]
Sounds like this: https://github.com/qunitjs/qunit/issues/1284
but we obviously don't get the error

**Comment by gkatsev** [comment]
So, aside from the weird qunit issue, with summary-reporter and spec+suppressPassed it is better except for a small issue that makes it almost useless: there's no way to know which browser a particular failure is associated with https://travis-ci.org/videojs/video.js/builds/449412949

I'm OK with making spec the default and special-casing Video.js.

**Comment by ldayananda** [comment]
I believe Brandon is correct that the stack trace is a qunit issue, with `2.4.1` I didn't have the same problem. 

I think in our case, we would like `spec` over `summary-reporter` as you get the list of tests that ran and whether they passed or not (though you don't get the browser if tests are running concurrently in multiple browsers)

**Comment by brandonocasey** [comment]
It seems like we may just want to keep `dots` as the default, since that will report what browser it failed on. I would then think we could use `summary-reporter` with `suppressPassed` by default, and that could be turned off in your config.

**Comment by gkatsev** [comment]
`suppressPassed` is an option for the spec reporter. To me it seems like Video.js is more of the odd one out, fwiw. I do wish that the spec reporter logged which browser was being run, though.

**Comment by brandonocasey** [comment]
ahh I was thinking of `karma-summary-reporter` with `failed` vs `all`: https://github.com/sth/karma-summary-reporter thanks for the clarification.

**Comment by gkatsev** [comment]
Oh, looking at the summary-reporter again, I see that you can tell which browsers failed via its little table output. I don't think I understood how to read it before.

**Comment by gkatsev** [comment]
Also, maybe we should downgrade qunit to 2.4.1 until that weird issue is fixed?

**Comment by gkatsev** [comment]
So, I have less issues with making spec default and also including summary-reporter. Then videojs just just set `suppressPassed:true`

**Comment by brandonocasey** [comment]
I opened another issue for the `qunit` assertion stack trace weirdness #17

**Comment by brandonocasey** [comment]
@gkatsev I think the idea would be to keep dots, and to have `summary reporter` set to `all`. That would get us errors that we can track to browsers that are running concurrently, but also a summary of all the tests that ran, even those that passed.

**Comment by gkatsev** [comment]
The downside with that is when you're running it locally, you won't see the output until all tests are done. For Video.js we'd still want to keep it just as `failed`

**Comment by brandonocasey** [comment]
Yeah that would be the downside. Here is a branch/pr for testing with: https://github.com/videojs/videojs-generate-karma-config/compare/feat/summary-reporter
https://github.com/videojs/videojs-generate-karma-config/pull/19

**Comment by brandonocasey** [comment]
Another possible solution using spec, with dots to report errors, so we get browser context.
https://github.com/videojs/videojs-generate-karma-config/pull/20

**Comment by gkatsev** [comment]
So, after much more thought and trial, I think we should just stick to dots and document better how to override things. The needs in this area are too different and dots is an OK (and built-in) reporter.
