### ISSUE TITLE
 Cannot load browser "SafariTechPreview" while running unit tests.

### ISSUE THREAD

**Issue by hendrikras** [videojs/videojs-generate-karma-config#6]
generated a plugin project with yeoman generator. Tests fail with following output:

24 10 2018 15:23:52.215:INFO [launcher]: Launching browsers ChromeHeadless, FirefoxHeadless, Safari, SafariTechPreview with unlimited concurrency
24 10 2018 15:23:52.219:ERROR [launcher]: Cannot load browser "SafariTechPreview": it is not registered! Perhaps you are missing some plugin?
24 10 2018 15:23:52.219:ERROR [karma]: Error: Found 1 load error

**Comment by gkatsev** [comment]
Thanks, I have a fix for it in #7
